from enum import StrEnum


class Perm(StrEnum):
    TENANT_MANAGE_SETTINGS = "tenant.manage_settings"
    BRANCHES_READ = "branches.read"
    BRANCHES_CREATE = "branches.create"
    BRANCHES_UPDATE = "branches.update"
    BRANCHES_DELETE = "branches.delete"
    WAREHOUSES_READ = "warehouses.read"
    WAREHOUSES_CREATE = "warehouses.create"
    WAREHOUSES_UPDATE = "warehouses.update"
    WAREHOUSES_DELETE = "warehouses.delete"
    USERS_READ = "users.read"
    USERS_INVITE = "users.invite"
    USERS_MANAGE = "users.manage"
    USERS_MANAGE_ROLES = "users.manage_roles"
    ROLES_MANAGE = "roles.manage"
    AUDIT_READ = "audit.read"
    INVENTORY_READ = "inventory.read"
    INVENTORY_MANAGE = "inventory.manage"
    INVENTORY_RECEIVE = "inventory.receive"
    INVENTORY_ISSUE = "inventory.issue"
    INVENTORY_ADJUST = "inventory.adjust"
    INVENTORY_RESERVE = "inventory.reserve"
    INVENTORY_TRANSFER = "inventory.transfer"
    CUSTOMERS_READ = "customers.read"
    CUSTOMERS_MANAGE = "customers.manage"
    SUPPLIERS_READ = "suppliers.read"
    SUPPLIERS_MANAGE = "suppliers.manage"
    SALES_READ = "sales.read"
    SALES_MANAGE = "sales.manage"
    SALES_FULFILL = "sales.fulfill"
    SALES_INVOICE = "sales.invoice"
    SALES_PAYMENT = "sales.payment"
    PURCHASES_READ = "purchases.read"
    PURCHASES_MANAGE = "purchases.manage"
    PURCHASES_RECEIVE = "purchases.receive"
    PURCHASES_BILL = "purchases.bill"
    PURCHASES_PAYMENT = "purchases.payment"
    CRM_READ = "crm.read"
    CRM_MANAGE = "crm.manage"
    REPORTS_READ = "reports.read"
    POS_READ = "pos.read"
    POS_OPERATE = "pos.operate"
    POS_SESSION = "pos.session"
    POS_REFUND = "pos.refund"
    ACCOUNTING_READ = "accounting.read"
    ACCOUNTING_MANAGE = "accounting.manage"
    ACCOUNTING_POST = "accounting.post"
    ACCOUNTING_POST_CLOSED = "accounting.post_closed"


PHASE_1_PERMISSIONS = tuple(permission.value for permission in Perm)
