"""phase 2 catalog inventory

Revision ID: 0012_catalog_inventory
Revises: 0011_invitation_redemption
Create Date: 2026-08-29 15:47:27.662857
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0012_catalog_inventory"
down_revision: str | None = "0011_invitation_redemption"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = (
    "brands",
    "categories",
    "tax_categories",
    "units_of_measure",
    "products",
    "inventory_balances",
    "inventory_movements",
    "product_variants",
    "stock_adjustments",
    "stock_reservations",
    "stock_transfers",
    "product_barcodes",
    "stock_transfer_lines",
)

PHASE_2_PERMISSIONS = (
    "inventory.read",
    "inventory.manage",
    "inventory.receive",
    "inventory.issue",
    "inventory.adjust",
    "inventory.reserve",
    "inventory.transfer",
)

ROLE_PERMISSIONS = {
    "OWNER": PHASE_2_PERMISSIONS,
    "ADMIN": PHASE_2_PERMISSIONS,
    "MANAGER": ("inventory.read",),
    "ACCOUNTANT": ("inventory.read",),
    "INVENTORY_MANAGER": PHASE_2_PERMISSIONS,
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_brands_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
        sa.UniqueConstraint("tenant_id", "name", name=op.f("uq_brands_tenant_id_name")),
    )
    op.create_index(
        "ix_brands_tenant_id_is_active", "brands", ["tenant_id", "is_active"], unique=False
    )
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_categories_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint(
            "tenant_id",
            "parent_id",
            "name",
            name=op.f("uq_categories_tenant_id_parent_id_name"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_categories_tenant_id_name", "categories", ["tenant_id", "name"], unique=False
    )
    op.create_table(
        "tax_categories",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("rate", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rate >= 0 AND rate <= 1", name=op.f("ck_tax_categories_rate_range")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tax_categories_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_categories")),
        sa.UniqueConstraint("tenant_id", "code", name=op.f("uq_tax_categories_tenant_id_code")),
    )
    op.create_index(
        "ix_tax_categories_tenant_id_is_active",
        "tax_categories",
        ["tenant_id", "is_active"],
        unique=False,
    )
    op.create_table(
        "units_of_measure",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("precision", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "precision BETWEEN 0 AND 6", name=op.f("ck_units_of_measure_precision_range")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_units_of_measure_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units_of_measure")),
        sa.UniqueConstraint("tenant_id", "code", name=op.f("uq_units_of_measure_tenant_id_code")),
    )
    op.create_index(
        "ix_units_of_measure_tenant_id_is_active",
        "units_of_measure",
        ["tenant_id", "is_active"],
        unique=False,
    )
    op.create_table(
        "products",
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("brand_id", sa.Uuid(), nullable=True),
        sa.Column("uom_id", sa.Uuid(), nullable=False),
        sa.Column("tax_category_id", sa.Uuid(), nullable=True),
        sa.Column(
            "cost_price", sa.Numeric(precision=18, scale=6), server_default="0", nullable=False
        ),
        sa.Column(
            "selling_price", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column("reorder_point", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("is_stock_tracked", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("cost_price >= 0", name=op.f("ck_products_cost_price_nonnegative")),
        sa.CheckConstraint(
            "reorder_point IS NULL OR reorder_point >= 0",
            name=op.f("ck_products_reorder_nonnegative"),
        ),
        sa.CheckConstraint(
            "selling_price >= 0", name=op.f("ck_products_selling_price_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_products_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_products_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tax_category_id"],
            ["tax_categories.id"],
            name=op.f("fk_products_tax_category_id_tax_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_products_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uom_id"],
            ["units_of_measure.id"],
            name=op.f("fk_products_uom_id_units_of_measure"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("tenant_id", "sku", name=op.f("uq_products_tenant_id_sku")),
    )
    op.create_index(
        "ix_products_name_trgm",
        "products",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_products_tenant_id_is_active", "products", ["tenant_id", "is_active"], unique=False
    )
    op.create_table(
        "inventory_balances",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column(
            "quantity_on_hand",
            sa.Numeric(precision=20, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "reserved_quantity",
            sa.Numeric(precision=20, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reserved_quantity >= 0", name=op.f("ck_inventory_balances_reserved_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inventory_balances_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_inventory_balances_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_balances_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_balances")),
        sa.UniqueConstraint(
            "tenant_id",
            "warehouse_id",
            "product_id",
            name=op.f("uq_inventory_balances_tenant_id_warehouse_id_product_id"),
        ),
    )
    op.create_index(
        "ix_inventory_balances_tenant_product",
        "inventory_balances",
        ["tenant_id", "product_id"],
        unique=False,
    )
    op.create_table(
        "inventory_movements",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column(
            "movement_type",
            sa.Enum(
                "RECEIPT",
                "ISSUE",
                "ADJUSTMENT",
                "TRANSFER_IN",
                "TRANSFER_OUT",
                "SALE",
                "SALE_RETURN",
                "PURCHASE_RETURN",
                name="inventory_movement_type",
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("balance_after", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("reference_type", sa.String(length=64), nullable=True),
        sa.Column("reference_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_membership_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity <> 0", name=op.f("ck_inventory_movements_quantity_nonzero")),
        sa.ForeignKeyConstraint(
            ["created_by_membership_id"],
            ["memberships.id"],
            name=op.f("fk_inventory_movements_created_by_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inventory_movements_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_inventory_movements_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_movements_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_movements")),
    )
    op.create_index(
        "ix_inventory_movements_tenant_warehouse_product_occurred",
        "inventory_movements",
        ["tenant_id", "warehouse_id", "product_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "uq_inventory_movements_tenant_idempotency_key",
        "inventory_movements",
        ["tenant_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_table(
        "product_variants",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_variants_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_product_variants_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_variants")),
        sa.UniqueConstraint("id", "product_id", name="uq_product_variants_id_product"),
        sa.UniqueConstraint("tenant_id", "sku", name=op.f("uq_product_variants_tenant_id_sku")),
    )
    op.create_index(
        "ix_product_variants_tenant_id_product_id",
        "product_variants",
        ["tenant_id", "product_id"],
        unique=False,
    )
    op.create_table(
        "stock_adjustments",
        sa.Column("adjustment_number", sa.String(length=64), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("approved_by_membership_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity <> 0", name=op.f("ck_stock_adjustments_quantity_nonzero")),
        sa.ForeignKeyConstraint(
            ["approved_by_membership_id"],
            ["memberships.id"],
            name=op.f("fk_stock_adjustments_approved_by_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_stock_adjustments_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_stock_adjustments_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_stock_adjustments_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_adjustments")),
        sa.UniqueConstraint(
            "tenant_id",
            "adjustment_number",
            name=op.f("uq_stock_adjustments_tenant_id_adjustment_number"),
        ),
    )
    op.create_index(
        "ix_stock_adjustments_tenant_warehouse",
        "stock_adjustments",
        ["tenant_id", "warehouse_id"],
        unique=False,
    )
    op.create_table(
        "stock_reservations",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("reference_type", sa.String(length=64), nullable=False),
        sa.Column("reference_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "RELEASED", "CONSUMED", name="stock_reservation_status"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_stock_reservations_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_stock_reservations_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_stock_reservations_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_stock_reservations_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_reservations")),
    )
    op.create_index(
        "ix_stock_reservations_tenant_status_expires",
        "stock_reservations",
        ["tenant_id", "status", "expires_at"],
        unique=False,
    )
    op.create_table(
        "stock_transfers",
        sa.Column("transfer_number", sa.String(length=64), nullable=False),
        sa.Column("source_warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("destination_warehouse_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "IN_TRANSIT", "COMPLETED", "CANCELLED", name="stock_transfer_status"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_warehouse_id <> destination_warehouse_id",
            name=op.f("ck_stock_transfers_distinct_warehouses"),
        ),
        sa.ForeignKeyConstraint(
            ["destination_warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_stock_transfers_destination_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_stock_transfers_source_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_stock_transfers_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_transfers")),
        sa.UniqueConstraint(
            "tenant_id",
            "transfer_number",
            name=op.f("uq_stock_transfers_tenant_id_transfer_number"),
        ),
    )
    op.create_index(
        "ix_stock_transfers_tenant_status", "stock_transfers", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "product_barcodes",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("product_variant_id", sa.Uuid(), nullable=True),
        sa.Column("barcode", sa.String(length=64), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_barcodes_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_variant_id", "product_id"],
            ["product_variants.id", "product_variants.product_id"],
            name="fk_product_barcodes_variant_matches_product",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_product_barcodes_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_barcodes")),
        sa.UniqueConstraint(
            "tenant_id", "barcode", name=op.f("uq_product_barcodes_tenant_id_barcode")
        ),
    )
    op.create_index(
        "ix_product_barcodes_tenant_id_product_id",
        "product_barcodes",
        ["tenant_id", "product_id"],
        unique=False,
    )
    op.create_table(
        "stock_transfer_lines",
        sa.Column("transfer_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_stock_transfer_lines_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_stock_transfer_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_stock_transfer_lines_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transfer_id"],
            ["stock_transfers.id"],
            name=op.f("fk_stock_transfer_lines_transfer_id_stock_transfers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_transfer_lines")),
        sa.UniqueConstraint(
            "tenant_id",
            "transfer_id",
            "product_id",
            name=op.f("uq_stock_transfer_lines_tenant_id_transfer_id_product_id"),
        ),
    )
    op.create_index(
        "ix_stock_transfer_lines_tenant_transfer",
        "stock_transfer_lines",
        ["tenant_id", "transfer_id"],
        unique=False,
    )
    for table in TENANT_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table}_updated_at BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION nexora_set_updated_at()"
        )
        # ENABLE only, never FORCE (ADR-0022, DATABASE.md §6.1). ENABLE already
        # polices every non-owner role, and `nexora_app` is a non-owner, so the
        # application is fully covered. FORCE additionally polices the *owner* —
        # `nexora_owner`, which runs migrations, seeding and maintenance — with
        # tenant predicates it can never satisfy. It bought nothing here and
        # would fail the first owner-run backfill over these tables.
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            "USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid) "
            "WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)"
        )

    op.execute(
        "CREATE TRIGGER trg_inventory_movements_immutable "
        "BEFORE UPDATE OR DELETE ON inventory_movements FOR EACH ROW "
        "EXECUTE FUNCTION nexora_block_mutation()"
    )
    op.execute("REVOKE UPDATE, DELETE ON inventory_movements FROM nexora_app")

    connection = op.get_bind()
    for permission in PHASE_2_PERMISSIONS:
        connection.execute(
            sa.text(
                "INSERT INTO permissions (code, description, module) "
                "VALUES (:code, :description, 'inventory')"
            ),
            {"code": permission, "description": permission.replace(".", " ").title()},
        )
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions DISABLE TRIGGER trg_role_permissions_system_immutable"
    )
    for role_code, permissions in ROLE_PERMISSIONS.items():
        for permission in permissions:
            connection.execute(
                sa.text(
                    "INSERT INTO role_permissions (role_id, permission_code) "
                    "SELECT id, :permission FROM roles WHERE code = :role_code AND is_system"
                ),
                {"role_code": role_code, "permission": permission},
            )
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions ENABLE TRIGGER trg_role_permissions_system_immutable"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    connection = op.get_bind()
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions DISABLE TRIGGER trg_role_permissions_system_immutable"
    )
    for permission in PHASE_2_PERMISSIONS:
        connection.execute(
            sa.text("DELETE FROM role_permissions WHERE permission_code = :permission"),
            {"permission": permission},
        )
        connection.execute(
            sa.text("DELETE FROM permissions WHERE code = :permission"),
            {"permission": permission},
        )
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions ENABLE TRIGGER trg_role_permissions_system_immutable"
    )
    op.execute("GRANT UPDATE, DELETE ON inventory_movements TO nexora_app")
    op.execute("DROP TRIGGER trg_inventory_movements_immutable ON inventory_movements")
    for table in reversed(TENANT_TABLES):
        op.execute(f"DROP POLICY tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
        op.execute(f"DROP TRIGGER trg_{table}_updated_at ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stock_transfer_lines_tenant_transfer", table_name="stock_transfer_lines")
    op.drop_table("stock_transfer_lines")
    op.drop_index("ix_product_barcodes_tenant_id_product_id", table_name="product_barcodes")
    op.drop_table("product_barcodes")
    op.drop_index("ix_stock_transfers_tenant_status", table_name="stock_transfers")
    op.drop_table("stock_transfers")
    op.drop_index("ix_stock_reservations_tenant_status_expires", table_name="stock_reservations")
    op.drop_table("stock_reservations")
    op.drop_index("ix_stock_adjustments_tenant_warehouse", table_name="stock_adjustments")
    op.drop_table("stock_adjustments")
    op.drop_index("ix_product_variants_tenant_id_product_id", table_name="product_variants")
    op.drop_table("product_variants")
    op.drop_index(
        "uq_inventory_movements_tenant_idempotency_key",
        table_name="inventory_movements",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_index(
        "ix_inventory_movements_tenant_warehouse_product_occurred", table_name="inventory_movements"
    )
    op.drop_table("inventory_movements")
    op.drop_index("ix_inventory_balances_tenant_product", table_name="inventory_balances")
    op.drop_table("inventory_balances")
    op.drop_index("ix_products_tenant_id_is_active", table_name="products")
    op.drop_index(
        "ix_products_name_trgm",
        table_name="products",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("products")
    op.drop_index("ix_units_of_measure_tenant_id_is_active", table_name="units_of_measure")
    op.drop_table("units_of_measure")
    op.drop_index("ix_tax_categories_tenant_id_is_active", table_name="tax_categories")
    op.drop_table("tax_categories")
    op.drop_index("ix_categories_tenant_id_name", table_name="categories")
    op.drop_table("categories")
    op.drop_index("ix_brands_tenant_id_is_active", table_name="brands")
    op.drop_table("brands")
    for enum_name in (
        "stock_transfer_status",
        "stock_reservation_status",
        "inventory_movement_type",
    ):
        postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

    # Dropped last, after every table that uses them. Alembic's
    # autogenerate creates enum types but never drops them, so a downgrade
    # left them behind and the next upgrade failed with
    # `type "..." already exists`. Dropping them earlier fails the other
    # way, with DependentObjectsStillExistError.
    for enum_name in (
        "inventory_movement_type",
        "stock_reservation_status",
        "stock_transfer_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
