"""Phase 3 — parties, sales and purchasing documents.

RLS uses ENABLE only, never FORCE (ADR-0022, DATABASE.md §6.1).

Revision ID: 79979550ddf5
Revises: 0012_catalog_inventory
Create Date: 2026-08-29 17:21:24.412692
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0013_sales_purchasing"
down_revision: str | None = "0012_catalog_inventory"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = (
    "customers",
    "suppliers",
    "document_sequences",
    "quotations",
    "quotation_lines",
    "sales_orders",
    "sales_order_lines",
    "fulfillments",
    "fulfillment_lines",
    "invoices",
    "invoice_lines",
    "payments",
    "payment_allocations",
    "credit_notes",
    "credit_note_lines",
    "purchase_orders",
    "purchase_order_lines",
    "goods_receipts",
    "goods_receipt_lines",
    "supplier_bills",
    "supplier_bill_lines",
)

# API.md §6 reserves these namespaces; they are enforced from this phase.
PHASE_3_PERMISSIONS = (
    "customers.read",
    "customers.manage",
    "suppliers.read",
    "suppliers.manage",
    "sales.read",
    "sales.manage",
    "sales.fulfill",
    "sales.invoice",
    "sales.payment",
    "purchases.read",
    "purchases.manage",
    "purchases.receive",
    "purchases.bill",
    "purchases.payment",
)

# Without attaching these to the system roles, every new route 403s for
# everyone including OWNER, which reads as an authorization bug rather than
# missing seed data.
ROLE_PERMISSIONS = {
    "MANAGER": PHASE_3_PERMISSIONS,
    "ACCOUNTANT": (
        "customers.read",
        "suppliers.read",
        "sales.read",
        "sales.invoice",
        "sales.payment",
        "purchases.read",
        "purchases.bill",
        "purchases.payment",
    ),
    "SALES": (
        "customers.read",
        "customers.manage",
        "sales.read",
        "sales.manage",
        "sales.fulfill",
        "sales.invoice",
    ),
    "INVENTORY_MANAGER": (
        "suppliers.read",
        "purchases.read",
        "purchases.receive",
        "sales.read",
        "sales.fulfill",
    ),
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("tax_number", sa.String(length=64), nullable=True),
        sa.Column("billing_address", sa.Text(), nullable=True),
        sa.Column("shipping_address", sa.Text(), nullable=True),
        sa.Column(
            "credit_limit", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column("credit_limit_enforced", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("credit_limit >= 0", name=op.f("ck_customers_credit_limit_nonnegative")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_customers_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("tenant_id", "code", name=op.f("uq_customers_tenant_id_code")),
    )
    op.create_index(
        "ix_customers_name_trgm",
        "customers",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_customers_tenant_id_is_active", "customers", ["tenant_id", "is_active"], unique=False
    )
    op.create_table(
        "document_sequences",
        sa.Column("series", sa.String(length=32), nullable=False),
        sa.Column("period", sa.String(length=16), nullable=False),
        sa.Column("next_value", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("prefix", sa.String(length=16), server_default="", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "next_value >= 1", name=op.f("ck_document_sequences_next_value_positive")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_document_sequences_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_sequences")),
        sa.UniqueConstraint(
            "tenant_id",
            "series",
            "period",
            name=op.f("uq_document_sequences_tenant_id_series_period"),
        ),
    )
    op.create_table(
        "suppliers",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("tax_number", sa.String(length=64), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("payment_terms_days", sa.Integer(), server_default="0", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_suppliers_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
        sa.UniqueConstraint("tenant_id", "code", name=op.f("uq_suppliers_tenant_id_code")),
    )
    op.create_index(
        "ix_suppliers_name_trgm",
        "suppliers",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_suppliers_tenant_id_is_active", "suppliers", ["tenant_id", "is_active"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("payment_number", sa.String(length=64), nullable=False),
        sa.Column(
            "direction", sa.Enum("INBOUND", "OUTBOUND", name="payment_direction"), nullable=False
        ),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column(
            "method",
            sa.Enum("CASH", "CARD", "BANK_TRANSFER", "MOBILE", "CREDIT", name="payment_method"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "allocated_amount",
            sa.Numeric(precision=18, scale=4),
            server_default="0",
            nullable=False,
        ),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(direction = 'INBOUND'  AND customer_id IS NOT NULL AND supplier_id IS NULL) OR "
            "(direction = 'OUTBOUND' AND supplier_id IS NOT NULL AND customer_id IS NULL)",
            name=op.f("ck_payments_counterparty_matches_direction"),
        ),
        sa.CheckConstraint(
            "allocated_amount >= 0 AND allocated_amount <= amount",
            name=op.f("ck_payments_allocated_within_amount"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f("fk_payments_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_payments_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_payments_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_payments_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint(
            "tenant_id", "payment_number", name=op.f("uq_payments_tenant_id_payment_number")
        ),
    )
    op.create_index(
        "ix_payments_tenant_id_customer_id", "payments", ["tenant_id", "customer_id"], unique=False
    )
    op.create_index(
        "ix_payments_tenant_id_direction", "payments", ["tenant_id", "direction"], unique=False
    )
    op.create_index(
        "ix_payments_tenant_id_supplier_id", "payments", ["tenant_id", "supplier_id"], unique=False
    )
    op.create_table(
        "quotations",
        sa.Column("quotation_number", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "SENT", "ACCEPTED", "REJECTED", "EXPIRED", name="quotation_status"),
            nullable=False,
        ),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column(
            "net_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "tax_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "total_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("converted_order_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("total_amount >= 0", name=op.f("ck_quotations_total_nonnegative")),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f("fk_quotations_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_quotations_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_quotations_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotations")),
        sa.UniqueConstraint(
            "tenant_id", "quotation_number", name=op.f("uq_quotations_tenant_id_quotation_number")
        ),
    )
    op.create_index(
        "ix_quotations_tenant_id_status", "quotations", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "purchase_orders",
        sa.Column("order_number", sa.String(length=64), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "CONFIRMED",
                "PARTIALLY_RECEIVED",
                "RECEIVED",
                "CANCELLED",
                name="purchase_order_status",
            ),
            nullable=False,
        ),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("expected_date", sa.Date(), nullable=True),
        sa.Column(
            "net_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "tax_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "total_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("total_amount >= 0", name=op.f("ck_purchase_orders_total_nonnegative")),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f("fk_purchase_orders_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_purchase_orders_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_purchase_orders_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_purchase_orders_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_orders")),
        sa.UniqueConstraint(
            "tenant_id", "order_number", name=op.f("uq_purchase_orders_tenant_id_order_number")
        ),
    )
    op.create_index(
        "ix_purchase_orders_tenant_id_status",
        "purchase_orders",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_purchase_orders_tenant_id_supplier_id",
        "purchase_orders",
        ["tenant_id", "supplier_id"],
        unique=False,
    )
    op.create_table(
        "quotation_lines",
        sa.Column("quotation_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "discount_rate", sa.Numeric(precision=9, scale=6), server_default="0", nullable=False
        ),
        sa.Column("tax_rate", sa.Numeric(precision=9, scale=6), server_default="0", nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_quotation_lines_quantity_positive")),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_quotation_lines_unit_price_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_quotation_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["quotation_id"],
            ["quotations.id"],
            name=op.f("fk_quotation_lines_quotation_id_quotations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_quotation_lines_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotation_lines")),
    )
    op.create_index(
        "ix_quotation_lines_tenant_id_quotation_id",
        "quotation_lines",
        ["tenant_id", "quotation_id"],
        unique=False,
    )
    op.create_table(
        "sales_orders",
        sa.Column("order_number", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("quotation_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "CONFIRMED",
                "PARTIALLY_FULFILLED",
                "FULFILLED",
                "CANCELLED",
                name="sales_order_status",
            ),
            nullable=False,
        ),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column(
            "net_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "tax_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "total_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("total_amount >= 0", name=op.f("ck_sales_orders_total_nonnegative")),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f("fk_sales_orders_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_sales_orders_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["quotation_id"],
            ["quotations.id"],
            name=op.f("fk_sales_orders_quotation_id_quotations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_sales_orders_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_sales_orders_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_orders")),
        sa.UniqueConstraint(
            "tenant_id", "order_number", name=op.f("uq_sales_orders_tenant_id_order_number")
        ),
    )
    op.create_index(
        "ix_sales_orders_tenant_id_customer_id",
        "sales_orders",
        ["tenant_id", "customer_id"],
        unique=False,
    )
    op.create_index(
        "ix_sales_orders_tenant_id_status", "sales_orders", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "fulfillments",
        sa.Column("fulfillment_number", sa.String(length=64), nullable=False),
        sa.Column("sales_order_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sales_order_id"],
            ["sales_orders.id"],
            name=op.f("fk_fulfillments_sales_order_id_sales_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_fulfillments_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_fulfillments_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fulfillments")),
        sa.UniqueConstraint(
            "tenant_id",
            "fulfillment_number",
            name=op.f("uq_fulfillments_tenant_id_fulfillment_number"),
        ),
    )
    op.create_index(
        "ix_fulfillments_tenant_id_sales_order_id",
        "fulfillments",
        ["tenant_id", "sales_order_id"],
        unique=False,
    )
    op.create_table(
        "goods_receipts",
        sa.Column("receipt_number", sa.String(length=64), nullable=False),
        sa.Column("purchase_order_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("supplier_reference", sa.String(length=120), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_goods_receipts_purchase_order_id_purchase_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_goods_receipts_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_goods_receipts_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goods_receipts")),
        sa.UniqueConstraint(
            "tenant_id", "receipt_number", name=op.f("uq_goods_receipts_tenant_id_receipt_number")
        ),
    )
    op.create_index(
        "ix_goods_receipts_tenant_id_po_id",
        "goods_receipts",
        ["tenant_id", "purchase_order_id"],
        unique=False,
    )
    op.create_table(
        "invoices",
        sa.Column("invoice_number", sa.String(length=64), nullable=True),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("sales_order_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "ISSUED", "PARTIALLY_PAID", "PAID", "CANCELLED", name="invoice_status"
            ),
            nullable=False,
        ),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "net_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "tax_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "total_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "paid_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "paid_amount >= 0 AND paid_amount <= total_amount",
            name=op.f("ck_invoices_paid_within_total"),
        ),
        sa.CheckConstraint("total_amount >= 0", name=op.f("ck_invoices_total_nonnegative")),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f("fk_invoices_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_invoices_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sales_order_id"],
            ["sales_orders.id"],
            name=op.f("fk_invoices_sales_order_id_sales_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_invoices_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
        sa.UniqueConstraint(
            "tenant_id", "invoice_number", name=op.f("uq_invoices_tenant_id_invoice_number")
        ),
    )
    op.create_index(
        "ix_invoices_tenant_id_customer_id", "invoices", ["tenant_id", "customer_id"], unique=False
    )
    op.create_index(
        "ix_invoices_tenant_id_due_date", "invoices", ["tenant_id", "due_date"], unique=False
    )
    op.create_index(
        "ix_invoices_tenant_id_status", "invoices", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "purchase_order_lines",
        sa.Column("purchase_order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=9, scale=6), server_default="0", nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "received_quantity",
            sa.Numeric(precision=20, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "billed_quantity", sa.Numeric(precision=20, scale=6), server_default="0", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "billed_quantity >= 0 AND billed_quantity <= quantity",
            name=op.f("ck_purchase_order_lines_billed_within_ordered"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_purchase_order_lines_quantity_positive")),
        sa.CheckConstraint(
            "received_quantity >= 0 AND received_quantity <= quantity",
            name=op.f("ck_purchase_order_lines_received_within_ordered"),
        ),
        sa.CheckConstraint(
            "unit_cost >= 0", name=op.f("ck_purchase_order_lines_unit_cost_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_purchase_order_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_purchase_order_lines_purchase_order_id_purchase_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_purchase_order_lines_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_order_lines")),
        sa.UniqueConstraint(
            "tenant_id",
            "purchase_order_id",
            "product_id",
            name=op.f("uq_purchase_order_lines_tenant_id_purchase_order_id_product_id"),
        ),
    )
    op.create_index(
        "ix_purchase_order_lines_tenant_id_po_id",
        "purchase_order_lines",
        ["tenant_id", "purchase_order_id"],
        unique=False,
    )
    op.create_table(
        "sales_order_lines",
        sa.Column("sales_order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "fulfilled_quantity",
            sa.Numeric(precision=20, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "invoiced_quantity",
            sa.Numeric(precision=20, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "discount_rate", sa.Numeric(precision=9, scale=6), server_default="0", nullable=False
        ),
        sa.Column("tax_rate", sa.Numeric(precision=9, scale=6), server_default="0", nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.CheckConstraint(
            "fulfilled_quantity >= 0 AND fulfilled_quantity <= quantity",
            name=op.f("ck_sales_order_lines_fulfilled_within_ordered"),
        ),
        sa.CheckConstraint(
            "invoiced_quantity >= 0 AND invoiced_quantity <= quantity",
            name=op.f("ck_sales_order_lines_invoiced_within_ordered"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_sales_order_lines_quantity_positive")),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_sales_order_lines_unit_price_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_sales_order_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sales_order_id"],
            ["sales_orders.id"],
            name=op.f("fk_sales_order_lines_sales_order_id_sales_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_sales_order_lines_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_order_lines")),
        sa.UniqueConstraint(
            "tenant_id",
            "sales_order_id",
            "product_id",
            name=op.f("uq_sales_order_lines_tenant_id_sales_order_id_product_id"),
        ),
    )
    op.create_index(
        "ix_sales_order_lines_tenant_id_sales_order_id",
        "sales_order_lines",
        ["tenant_id", "sales_order_id"],
        unique=False,
    )
    op.create_table(
        "supplier_bills",
        sa.Column("bill_number", sa.String(length=64), nullable=True),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("purchase_order_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ISSUED",
                "PARTIALLY_PAID",
                "PAID",
                "CANCELLED",
                name="supplier_bill_status",
            ),
            nullable=False,
        ),
        sa.Column("supplier_invoice_number", sa.String(length=64), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "net_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "tax_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "total_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "paid_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "paid_amount >= 0 AND paid_amount <= total_amount",
            name=op.f("ck_supplier_bills_paid_within_total"),
        ),
        sa.CheckConstraint("total_amount >= 0", name=op.f("ck_supplier_bills_total_nonnegative")),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f("fk_supplier_bills_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_supplier_bills_purchase_order_id_purchase_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_supplier_bills_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_supplier_bills_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier_bills")),
        sa.UniqueConstraint(
            "tenant_id", "bill_number", name=op.f("uq_supplier_bills_tenant_id_bill_number")
        ),
    )
    op.create_index(
        "ix_supplier_bills_tenant_id_due_date",
        "supplier_bills",
        ["tenant_id", "due_date"],
        unique=False,
    )
    op.create_index(
        "ix_supplier_bills_tenant_id_status",
        "supplier_bills",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_supplier_bills_tenant_id_supplier_id",
        "supplier_bills",
        ["tenant_id", "supplier_id"],
        unique=False,
    )
    op.create_table(
        "credit_notes",
        sa.Column("credit_note_number", sa.String(length=64), nullable=True),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "ISSUED", "CANCELLED", name="credit_note_status"),
            nullable=False,
        ),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("restock", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=True),
        sa.Column(
            "net_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "tax_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "total_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("total_amount >= 0", name=op.f("ck_credit_notes_total_nonnegative")),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f("fk_credit_notes_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_credit_notes_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_credit_notes_invoice_id_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_credit_notes_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_credit_notes_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_notes")),
        sa.UniqueConstraint(
            "tenant_id",
            "credit_note_number",
            name=op.f("uq_credit_notes_tenant_id_credit_note_number"),
        ),
    )
    op.create_index(
        "ix_credit_notes_tenant_id_invoice_id",
        "credit_notes",
        ["tenant_id", "invoice_id"],
        unique=False,
    )
    op.create_table(
        "fulfillment_lines",
        sa.Column("fulfillment_id", sa.Uuid(), nullable=False),
        sa.Column("sales_order_line_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_fulfillment_lines_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["fulfillment_id"],
            ["fulfillments.id"],
            name=op.f("fk_fulfillment_lines_fulfillment_id_fulfillments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_fulfillment_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sales_order_line_id"],
            ["sales_order_lines.id"],
            name=op.f("fk_fulfillment_lines_sales_order_line_id_sales_order_lines"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_fulfillment_lines_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fulfillment_lines")),
    )
    op.create_index(
        "ix_fulfillment_lines_tenant_id_fulfillment_id",
        "fulfillment_lines",
        ["tenant_id", "fulfillment_id"],
        unique=False,
    )
    op.create_table(
        "goods_receipt_lines",
        sa.Column("goods_receipt_id", sa.Uuid(), nullable=False),
        sa.Column("purchase_order_line_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_goods_receipt_lines_quantity_positive")),
        sa.CheckConstraint(
            "unit_cost >= 0", name=op.f("ck_goods_receipt_lines_unit_cost_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["goods_receipt_id"],
            ["goods_receipts.id"],
            name=op.f("fk_goods_receipt_lines_goods_receipt_id_goods_receipts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_goods_receipt_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_line_id"],
            ["purchase_order_lines.id"],
            name=op.f("fk_goods_receipt_lines_purchase_order_line_id_purchase_order_lines"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_goods_receipt_lines_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goods_receipt_lines")),
    )
    op.create_index(
        "ix_goods_receipt_lines_tenant_id_receipt_id",
        "goods_receipt_lines",
        ["tenant_id", "goods_receipt_id"],
        unique=False,
    )
    op.create_table(
        "invoice_lines",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("sales_order_line_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "discount_rate", sa.Numeric(precision=9, scale=6), server_default="0", nullable=False
        ),
        sa.Column("tax_rate", sa.Numeric(precision=9, scale=6), server_default="0", nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_invoice_lines_quantity_positive")),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_invoice_lines_unit_price_nonnegative")),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_invoice_lines_invoice_id_invoices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_invoice_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sales_order_line_id"],
            ["sales_order_lines.id"],
            name=op.f("fk_invoice_lines_sales_order_line_id_sales_order_lines"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_invoice_lines_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_lines")),
    )
    op.create_index(
        "ix_invoice_lines_tenant_id_invoice_id",
        "invoice_lines",
        ["tenant_id", "invoice_id"],
        unique=False,
    )
    op.create_table(
        "payment_allocations",
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=True),
        sa.Column("supplier_bill_id", sa.Uuid(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(invoice_id IS NOT NULL AND supplier_bill_id IS NULL) OR "
            "(supplier_bill_id IS NOT NULL AND invoice_id IS NULL)",
            name=op.f("ck_payment_allocations_exactly_one_target"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payment_allocations_amount_positive")),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_payment_allocations_invoice_id_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            name=op.f("fk_payment_allocations_payment_id_payments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_bill_id"],
            ["supplier_bills.id"],
            name=op.f("fk_payment_allocations_supplier_bill_id_supplier_bills"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_payment_allocations_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_allocations")),
        sa.UniqueConstraint(
            "tenant_id",
            "payment_id",
            "invoice_id",
            name=op.f("uq_payment_allocations_tenant_id_payment_id_invoice_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "payment_id",
            "supplier_bill_id",
            name=op.f("uq_payment_allocations_tenant_id_payment_id_supplier_bill_id"),
        ),
    )
    op.create_index(
        "ix_payment_allocations_tenant_id_invoice_id",
        "payment_allocations",
        ["tenant_id", "invoice_id"],
        unique=False,
    )
    op.create_index(
        "ix_payment_allocations_tenant_id_payment_id",
        "payment_allocations",
        ["tenant_id", "payment_id"],
        unique=False,
    )
    op.create_table(
        "supplier_bill_lines",
        sa.Column("supplier_bill_id", sa.Uuid(), nullable=False),
        sa.Column("purchase_order_line_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=9, scale=6), server_default="0", nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_supplier_bill_lines_quantity_positive")),
        sa.CheckConstraint(
            "unit_cost >= 0", name=op.f("ck_supplier_bill_lines_unit_cost_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_supplier_bill_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_line_id"],
            ["purchase_order_lines.id"],
            name=op.f("fk_supplier_bill_lines_purchase_order_line_id_purchase_order_lines"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_bill_id"],
            ["supplier_bills.id"],
            name=op.f("fk_supplier_bill_lines_supplier_bill_id_supplier_bills"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_supplier_bill_lines_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier_bill_lines")),
    )
    op.create_index(
        "ix_supplier_bill_lines_tenant_id_bill_id",
        "supplier_bill_lines",
        ["tenant_id", "supplier_bill_id"],
        unique=False,
    )
    op.create_table(
        "credit_note_lines",
        sa.Column("credit_note_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_line_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "discount_rate", sa.Numeric(precision=9, scale=6), server_default="0", nullable=False
        ),
        sa.Column("tax_rate", sa.Numeric(precision=9, scale=6), server_default="0", nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_credit_note_lines_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["credit_note_id"],
            ["credit_notes.id"],
            name=op.f("fk_credit_note_lines_credit_note_id_credit_notes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_line_id"],
            ["invoice_lines.id"],
            name=op.f("fk_credit_note_lines_invoice_line_id_invoice_lines"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_credit_note_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_credit_note_lines_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_note_lines")),
    )
    op.create_index(
        "ix_credit_note_lines_tenant_id_credit_note_id",
        "credit_note_lines",
        ["tenant_id", "credit_note_id"],
        unique=False,
    )

    for table in TENANT_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table}_updated_at BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION nexora_set_updated_at()"
        )
        # ENABLE only, never FORCE (ADR-0022). FORCE also polices the owner,
        # which runs migrations and maintenance, against predicates it cannot
        # satisfy; `nexora_app` is a non-owner so ENABLE already covers the app.
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            "USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid) "
            "WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)"
        )

    connection = op.get_bind()
    for permission in PHASE_3_PERMISSIONS:
        module = permission.split(".")[0]
        connection.execute(
            sa.text(
                "INSERT INTO permissions (code, description, module) "
                "VALUES (:code, :description, :module)"
            ),
            {
                "code": permission,
                "description": permission.replace(".", " ").title(),
                "module": module,
            },
        )
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions DISABLE TRIGGER trg_role_permissions_system_immutable"
    )
    for role_code, permissions in ROLE_PERMISSIONS.items():
        for permission in permissions:
            connection.execute(
                sa.text(
                    "INSERT INTO role_permissions (role_id, permission_code) "
                    "SELECT id, :permission FROM roles WHERE code = :role_code AND is_system"
                ),
                {"role_code": role_code, "permission": permission},
            )
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions ENABLE TRIGGER trg_role_permissions_system_immutable"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    connection = op.get_bind()
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions DISABLE TRIGGER trg_role_permissions_system_immutable"
    )
    for permission in PHASE_3_PERMISSIONS:
        connection.execute(
            sa.text("DELETE FROM role_permissions WHERE permission_code = :permission"),
            {"permission": permission},
        )
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions ENABLE TRIGGER trg_role_permissions_system_immutable"
    )
    for permission in PHASE_3_PERMISSIONS:
        connection.execute(
            sa.text("DELETE FROM permissions WHERE code = :code"), {"code": permission}
        )
    for table in reversed(TENANT_TABLES):
        op.execute(f"DROP POLICY tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
        op.execute(f"DROP TRIGGER trg_{table}_updated_at ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_credit_note_lines_tenant_id_credit_note_id", table_name="credit_note_lines")
    op.drop_table("credit_note_lines")
    op.drop_index("ix_supplier_bill_lines_tenant_id_bill_id", table_name="supplier_bill_lines")
    op.drop_table("supplier_bill_lines")
    op.drop_index("ix_payment_allocations_tenant_id_payment_id", table_name="payment_allocations")
    op.drop_index("ix_payment_allocations_tenant_id_invoice_id", table_name="payment_allocations")
    op.drop_table("payment_allocations")
    op.drop_index("ix_invoice_lines_tenant_id_invoice_id", table_name="invoice_lines")
    op.drop_table("invoice_lines")
    op.drop_index("ix_goods_receipt_lines_tenant_id_receipt_id", table_name="goods_receipt_lines")
    op.drop_table("goods_receipt_lines")
    op.drop_index("ix_fulfillment_lines_tenant_id_fulfillment_id", table_name="fulfillment_lines")
    op.drop_table("fulfillment_lines")
    op.drop_index("ix_credit_notes_tenant_id_invoice_id", table_name="credit_notes")
    op.drop_table("credit_notes")
    op.drop_index("ix_supplier_bills_tenant_id_supplier_id", table_name="supplier_bills")
    op.drop_index("ix_supplier_bills_tenant_id_status", table_name="supplier_bills")
    op.drop_index("ix_supplier_bills_tenant_id_due_date", table_name="supplier_bills")
    op.drop_table("supplier_bills")
    op.drop_index("ix_sales_order_lines_tenant_id_sales_order_id", table_name="sales_order_lines")
    op.drop_table("sales_order_lines")
    op.drop_index("ix_purchase_order_lines_tenant_id_po_id", table_name="purchase_order_lines")
    op.drop_table("purchase_order_lines")
    op.drop_index("ix_invoices_tenant_id_status", table_name="invoices")
    op.drop_index("ix_invoices_tenant_id_due_date", table_name="invoices")
    op.drop_index("ix_invoices_tenant_id_customer_id", table_name="invoices")
    op.drop_table("invoices")
    op.drop_index("ix_goods_receipts_tenant_id_po_id", table_name="goods_receipts")
    op.drop_table("goods_receipts")
    op.drop_index("ix_fulfillments_tenant_id_sales_order_id", table_name="fulfillments")
    op.drop_table("fulfillments")
    op.drop_index("ix_sales_orders_tenant_id_status", table_name="sales_orders")
    op.drop_index("ix_sales_orders_tenant_id_customer_id", table_name="sales_orders")
    op.drop_table("sales_orders")
    op.drop_index("ix_quotation_lines_tenant_id_quotation_id", table_name="quotation_lines")
    op.drop_table("quotation_lines")
    op.drop_index("ix_purchase_orders_tenant_id_supplier_id", table_name="purchase_orders")
    op.drop_index("ix_purchase_orders_tenant_id_status", table_name="purchase_orders")
    op.drop_table("purchase_orders")
    op.drop_index("ix_quotations_tenant_id_status", table_name="quotations")
    op.drop_table("quotations")
    op.drop_index("ix_payments_tenant_id_supplier_id", table_name="payments")
    op.drop_index("ix_payments_tenant_id_direction", table_name="payments")
    op.drop_index("ix_payments_tenant_id_customer_id", table_name="payments")
    op.drop_table("payments")
    op.drop_index("ix_suppliers_tenant_id_is_active", table_name="suppliers")
    op.drop_index(
        "ix_suppliers_name_trgm",
        table_name="suppliers",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("suppliers")
    op.drop_table("document_sequences")
    op.drop_index("ix_customers_tenant_id_is_active", table_name="customers")
    op.drop_index(
        "ix_customers_name_trgm",
        table_name="customers",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("customers")
    # ### end Alembic commands ###

    # Dropped last, after every table that uses them. Alembic's
    # autogenerate creates enum types but never drops them, so a downgrade
    # left them behind and the next upgrade failed with
    # `type "..." already exists`. Dropping them earlier fails the other
    # way, with DependentObjectsStillExistError.
    for enum_name in (
        "quotation_status",
        "sales_order_status",
        "invoice_status",
        "payment_direction",
        "payment_method",
        "credit_note_status",
        "purchase_order_status",
        "supplier_bill_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
