"""phase 4 pos

Revision ID: 0015_pos
Revises: 0014_membership_role_self_access
Create Date: 2026-08-29 23:13:39.969993
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0015_pos"
down_revision: str | None = "0014_membership_role_self_access"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = (
    "pos_terminals",
    "pos_sessions",
    "sales",
    "sale_lines",
    "sale_payments",
    "held_sales",
    "receipts",
    "sale_returns",
    "sale_return_lines",
)
POS_PERMISSIONS = ("pos.read", "pos.operate", "pos.session", "pos.refund")
ROLE_PERMISSIONS = {
    "OWNER": POS_PERMISSIONS,
    "ADMIN": POS_PERMISSIONS,
    "MANAGER": POS_PERMISSIONS,
    "CASHIER": ("pos.read", "pos.operate", "pos.session"),
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pos_terminals",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f("fk_pos_terminals_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pos_terminals_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_pos_terminals_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pos_terminals")),
        sa.UniqueConstraint("tenant_id", "code", name=op.f("uq_pos_terminals_tenant_id_code")),
    )
    op.create_index(
        "ix_pos_terminals_tenant_branch", "pos_terminals", ["tenant_id", "branch_id"], unique=False
    )
    op.create_table(
        "pos_sessions",
        sa.Column("session_number", sa.String(length=64), nullable=False),
        sa.Column("terminal_id", sa.Uuid(), nullable=False),
        sa.Column("opened_by_membership_id", sa.Uuid(), nullable=False),
        sa.Column("closed_by_membership_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.Enum("OPEN", "CLOSED", name="pos_session_status"), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opening_float", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("expected_cash", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("counted_cash", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("cash_variance", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "opening_float >= 0", name=op.f("ck_pos_sessions_opening_float_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_membership_id"],
            ["memberships.id"],
            name=op.f("fk_pos_sessions_closed_by_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_membership_id"],
            ["memberships.id"],
            name=op.f("fk_pos_sessions_opened_by_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pos_sessions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["terminal_id"],
            ["pos_terminals.id"],
            name=op.f("fk_pos_sessions_terminal_id_pos_terminals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pos_sessions")),
        sa.UniqueConstraint(
            "tenant_id", "session_number", name=op.f("uq_pos_sessions_tenant_id_session_number")
        ),
    )
    op.create_index(
        "ix_pos_sessions_tenant_status", "pos_sessions", ["tenant_id", "status"], unique=False
    )
    op.create_index(
        "uq_pos_sessions_open_terminal",
        "pos_sessions",
        ["terminal_id"],
        unique=True,
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    op.create_table(
        "held_sales",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("terminal_id", sa.Uuid(), nullable=False),
        sa.Column("held_by_membership_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column(
            "cart", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("held_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["held_by_membership_id"],
            ["memberships.id"],
            name=op.f("fk_held_sales_held_by_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["pos_sessions.id"],
            name=op.f("fk_held_sales_session_id_pos_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_held_sales_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["terminal_id"],
            ["pos_terminals.id"],
            name=op.f("fk_held_sales_terminal_id_pos_terminals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_held_sales")),
    )
    op.create_index(
        "ix_held_sales_tenant_session", "held_sales", ["tenant_id", "session_id"], unique=False
    )
    op.create_table(
        "sales",
        sa.Column("sale_number", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("terminal_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("cashier_membership_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Enum("COMPLETED", "VOIDED", name="pos_sale_status"), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "discount_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "cost_amount", sa.Numeric(precision=18, scale=6), server_default="0", nullable=False
        ),
        sa.Column(
            "refunded_amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "net_amount >= 0 AND tax_amount >= 0 AND total_amount >= 0",
            name=op.f("ck_sales_totals_nonnegative"),
        ),
        sa.CheckConstraint(
            "refunded_amount >= 0 AND refunded_amount <= total_amount",
            name=op.f("ck_sales_refund_within_total"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f("fk_sales_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cashier_membership_id"],
            ["memberships.id"],
            name=op.f("fk_sales_cashier_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_sales_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["pos_sessions.id"],
            name=op.f("fk_sales_session_id_pos_sessions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_sales_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["terminal_id"],
            ["pos_terminals.id"],
            name=op.f("fk_sales_terminal_id_pos_terminals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_sales_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales")),
        sa.UniqueConstraint(
            "tenant_id", "sale_number", name=op.f("uq_sales_tenant_id_sale_number")
        ),
    )
    op.create_index("ix_sales_tenant_occurred", "sales", ["tenant_id", "occurred_at"], unique=False)
    op.create_index("ix_sales_tenant_session", "sales", ["tenant_id", "session_id"], unique=False)
    op.create_table(
        "receipts",
        sa.Column("receipt_number", sa.String(length=64), nullable=False),
        sa.Column("sale_id", sa.Uuid(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rendered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"], ["sales.id"], name=op.f("fk_receipts_sale_id_sales"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_receipts_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipts")),
        sa.UniqueConstraint(
            "tenant_id", "receipt_number", name=op.f("uq_receipts_tenant_id_receipt_number")
        ),
        sa.UniqueConstraint("tenant_id", "sale_id", name=op.f("uq_receipts_tenant_id_sale_id")),
    )
    op.create_table(
        "sale_lines",
        sa.Column("sale_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "discount_rate", sa.Numeric(precision=9, scale=6), server_default="0", nullable=False
        ),
        sa.Column("tax_rate", sa.Numeric(precision=9, scale=6), server_default="0", nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column(
            "refunded_quantity",
            sa.Numeric(precision=20, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_sale_lines_quantity_positive")),
        sa.CheckConstraint(
            "refunded_quantity >= 0 AND refunded_quantity <= quantity",
            name=op.f("ck_sale_lines_refund_within_quantity"),
        ),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_sale_lines_price_nonnegative")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_sale_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"], ["sales.id"], name=op.f("fk_sale_lines_sale_id_sales"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_sale_lines_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_lines")),
    )
    op.create_index(
        "ix_sale_lines_tenant_sale", "sale_lines", ["tenant_id", "sale_id"], unique=False
    )
    op.create_table(
        "sale_payments",
        sa.Column("sale_id", sa.Uuid(), nullable=False),
        sa.Column(
            "tender",
            sa.Enum("CASH", "CARD", "MOBILE", "VOUCHER", name="pos_tender_type"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "change_given", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "tender = 'CASH' OR change_given = 0", name=op.f("ck_sale_payments_change_cash_only")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_sale_payments_amount_positive")),
        sa.CheckConstraint(
            "change_given >= 0 AND change_given <= amount",
            name=op.f("ck_sale_payments_change_within_amount"),
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"],
            ["sales.id"],
            name=op.f("fk_sale_payments_sale_id_sales"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_sale_payments_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_payments")),
    )
    op.create_index(
        "ix_sale_payments_tenant_sale", "sale_payments", ["tenant_id", "sale_id"], unique=False
    )
    op.create_table(
        "sale_returns",
        sa.Column("return_number", sa.String(length=64), nullable=False),
        sa.Column("sale_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("processed_by_membership_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["processed_by_membership_id"],
            ["memberships.id"],
            name=op.f("fk_sale_returns_processed_by_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"],
            ["sales.id"],
            name=op.f("fk_sale_returns_sale_id_sales"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["pos_sessions.id"],
            name=op.f("fk_sale_returns_session_id_pos_sessions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_sale_returns_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_returns")),
        sa.UniqueConstraint(
            "tenant_id", "return_number", name=op.f("uq_sale_returns_tenant_id_return_number")
        ),
    )
    op.create_index(
        "ix_sale_returns_tenant_sale", "sale_returns", ["tenant_id", "sale_id"], unique=False
    )
    op.create_table(
        "sale_return_lines",
        sa.Column("sale_return_id", sa.Uuid(), nullable=False),
        sa.Column("sale_line_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_sale_return_lines_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_sale_return_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sale_line_id"],
            ["sale_lines.id"],
            name=op.f("fk_sale_return_lines_sale_line_id_sale_lines"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sale_return_id"],
            ["sale_returns.id"],
            name=op.f("fk_sale_return_lines_sale_return_id_sale_returns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_sale_return_lines_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_return_lines")),
    )
    op.create_index(
        "ix_sale_return_lines_tenant_return",
        "sale_return_lines",
        ["tenant_id", "sale_return_id"],
        unique=False,
    )
    for table in TENANT_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table}_updated_at BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION nexora_set_updated_at()"
        )
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            "USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid) "
            "WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)"
        )

    connection = op.get_bind()
    for permission in POS_PERMISSIONS:
        connection.execute(
            sa.text(
                "INSERT INTO permissions (code, description, module) "
                "VALUES (:code, :description, 'pos')"
            ),
            {"code": permission, "description": permission.replace(".", " ").title()},
        )
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions DISABLE TRIGGER trg_role_permissions_system_immutable"
    )
    for role_code, permissions in ROLE_PERMISSIONS.items():
        for permission in permissions:
            connection.execute(
                sa.text(
                    "INSERT INTO role_permissions (role_id, permission_code) "
                    "SELECT id, :permission FROM roles "
                    "WHERE code = :role_code AND is_system"
                ),
                {"role_code": role_code, "permission": permission},
            )
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions ENABLE TRIGGER trg_role_permissions_system_immutable"
    )
    connection.exec_driver_sql("""
        UPDATE memberships SET roles_version = roles_version + 1
         WHERE id IN (
            SELECT mr.membership_id FROM membership_roles mr
              JOIN roles r ON r.id = mr.role_id
             WHERE r.is_system AND r.code IN ('OWNER', 'ADMIN', 'MANAGER', 'CASHIER')
         )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions DISABLE TRIGGER trg_role_permissions_system_immutable"
    )
    for permission in POS_PERMISSIONS:
        connection.execute(
            sa.text("DELETE FROM role_permissions WHERE permission_code = :permission"),
            {"permission": permission},
        )
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions ENABLE TRIGGER trg_role_permissions_system_immutable"
    )
    for permission in POS_PERMISSIONS:
        connection.execute(
            sa.text("DELETE FROM permissions WHERE code = :permission"),
            {"permission": permission},
        )
    for table in reversed(TENANT_TABLES):
        op.execute(f"DROP POLICY tenant_isolation ON {table}")
        op.execute(f"DROP TRIGGER trg_{table}_updated_at ON {table}")
    op.drop_index("ix_sale_return_lines_tenant_return", table_name="sale_return_lines")
    op.drop_table("sale_return_lines")
    op.drop_index("ix_sale_returns_tenant_sale", table_name="sale_returns")
    op.drop_table("sale_returns")
    op.drop_index("ix_sale_payments_tenant_sale", table_name="sale_payments")
    op.drop_table("sale_payments")
    op.drop_index("ix_sale_lines_tenant_sale", table_name="sale_lines")
    op.drop_table("sale_lines")
    op.drop_table("receipts")
    op.drop_index("ix_sales_tenant_session", table_name="sales")
    op.drop_index("ix_sales_tenant_occurred", table_name="sales")
    op.drop_table("sales")
    op.drop_index("ix_held_sales_tenant_session", table_name="held_sales")
    op.drop_table("held_sales")
    op.drop_index(
        "uq_pos_sessions_open_terminal",
        table_name="pos_sessions",
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    op.drop_index("ix_pos_sessions_tenant_status", table_name="pos_sessions")
    op.drop_table("pos_sessions")
    op.drop_index("ix_pos_terminals_tenant_branch", table_name="pos_terminals")
    op.drop_table("pos_terminals")
    op.execute("DROP TYPE IF EXISTS pos_tender_type")
    op.execute("DROP TYPE IF EXISTS pos_sale_status")
    op.execute("DROP TYPE IF EXISTS pos_session_status")
    # ### end Alembic commands ###
