"""Phase 6 — CRM tables, permissions and RLS.

DATABASE.md §4 lists no Phase 6 tables; these are proposed in the Phase 6
handoff rather than given.

Revision ID: 01ffe59c2c6d
Revises: 0017_accounting
Create Date: 2026-08-30 00:46:07.696940
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0018_crm"
down_revision: str | None = "0017_accounting"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = ("leads", "opportunities", "crm_activities", "crm_notes")

# `reports.read` and the `crm.*` placeholder are already in the catalog from
# 0009, which seeded API.md §6's reserved namespaces. Only the concrete crm
# permissions are new here; the grants below still reference reports.read.
NEW_PERMISSIONS = ("crm.read", "crm.manage")
PERMISSIONS = ("crm.read", "crm.manage", "reports.read")

# Every role that can already see business data can read reports; only the
# commercial roles manage the pipeline.
ROLE_PERMISSIONS = {
    "OWNER": PERMISSIONS,
    "ADMIN": PERMISSIONS,
    "MANAGER": PERMISSIONS,
    "ACCOUNTANT": ("reports.read",),
    "SALES": PERMISSIONS,
    "INVENTORY_MANAGER": ("reports.read",),
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leads",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("company", sa.String(length=300), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column(
            "source",
            sa.Enum("WEB", "REFERRAL", "CAMPAIGN", "WALK_IN", "OTHER", name="crm_lead_source"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NEW", "CONTACTED", "QUALIFIED", "CONVERTED", "DISQUALIFIED", name="crm_lead_status"
            ),
            nullable=False,
        ),
        sa.Column("owner_membership_id", sa.Uuid(), nullable=True),
        sa.Column(
            "estimated_value", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column("converted_customer_id", sa.Uuid(), nullable=True),
        sa.Column("converted_opportunity_id", sa.Uuid(), nullable=True),
        sa.Column("converted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'CONVERTED' OR converted_customer_id IS NOT NULL",
            name=op.f("ck_leads_converted_lead_has_customer"),
        ),
        sa.CheckConstraint(
            "estimated_value >= 0", name=op.f("ck_leads_estimated_value_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["converted_customer_id"],
            ["customers.id"],
            name=op.f("fk_leads_converted_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_membership_id"],
            ["memberships.id"],
            name=op.f("fk_leads_owner_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_leads_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
        sa.UniqueConstraint("tenant_id", "code", name=op.f("uq_leads_tenant_id_code")),
    )
    op.create_index(
        "ix_leads_tenant_id_owner", "leads", ["tenant_id", "owner_membership_id"], unique=False
    )
    op.create_index("ix_leads_tenant_id_status", "leads", ["tenant_id", "status"], unique=False)
    op.create_table(
        "opportunities",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "PROSPECTING",
                "QUALIFICATION",
                "PROPOSAL",
                "NEGOTIATION",
                "WON",
                "LOST",
                name="crm_opportunity_stage",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False),
        sa.Column(
            "probability", sa.Numeric(precision=9, scale=6), server_default="0", nullable=False
        ),
        sa.Column("expected_close_date", sa.Date(), nullable=True),
        sa.Column("owner_membership_id", sa.Uuid(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lost_reason", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "stage <> 'LOST' OR lost_reason IS NOT NULL",
            name=op.f("ck_opportunities_lost_opportunity_has_reason"),
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_opportunities_amount_nonnegative")),
        sa.CheckConstraint(
            "probability >= 0 AND probability <= 1", name=op.f("ck_opportunities_probability_range")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_opportunities_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_membership_id"],
            ["memberships.id"],
            name=op.f("fk_opportunities_owner_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_opportunities_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunities")),
    )
    op.create_index(
        "ix_opportunities_tenant_id_customer_id",
        "opportunities",
        ["tenant_id", "customer_id"],
        unique=False,
    )
    op.create_index(
        "ix_opportunities_tenant_id_stage", "opportunities", ["tenant_id", "stage"], unique=False
    )
    op.create_table(
        "crm_activities",
        sa.Column(
            "activity_type",
            sa.Enum("CALL", "EMAIL", "MEETING", "TASK", name="crm_activity_type"),
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_membership_id", sa.Uuid(), nullable=True),
        sa.Column("lead_id", sa.Uuid(), nullable=True),
        sa.Column("opportunity_id", sa.Uuid(), nullable=True),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(CASE WHEN lead_id IS NOT NULL THEN 1 ELSE 0 END) + "
            "(CASE WHEN opportunity_id IS NOT NULL THEN 1 ELSE 0 END) + "
            "(CASE WHEN customer_id IS NOT NULL THEN 1 ELSE 0 END) = 1",
            name=op.f("ck_crm_activities_exactly_one_parent"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_crm_activities_customer_id_customers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
            name=op.f("fk_crm_activities_lead_id_leads"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_crm_activities_opportunity_id_opportunities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_membership_id"],
            ["memberships.id"],
            name=op.f("fk_crm_activities_owner_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_crm_activities_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crm_activities")),
    )
    op.create_index(
        "ix_crm_activities_tenant_id_due_at",
        "crm_activities",
        ["tenant_id", "due_at"],
        unique=False,
    )
    op.create_index(
        "ix_crm_activities_tenant_id_lead_id",
        "crm_activities",
        ["tenant_id", "lead_id"],
        unique=False,
    )
    op.create_index(
        "ix_crm_activities_tenant_id_opportunity_id",
        "crm_activities",
        ["tenant_id", "opportunity_id"],
        unique=False,
    )
    op.create_table(
        "crm_notes",
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("author_membership_id", sa.Uuid(), nullable=True),
        sa.Column("lead_id", sa.Uuid(), nullable=True),
        sa.Column("opportunity_id", sa.Uuid(), nullable=True),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(CASE WHEN lead_id IS NOT NULL THEN 1 ELSE 0 END) + "
            "(CASE WHEN opportunity_id IS NOT NULL THEN 1 ELSE 0 END) + "
            "(CASE WHEN customer_id IS NOT NULL THEN 1 ELSE 0 END) = 1",
            name=op.f("ck_crm_notes_exactly_one_parent"),
        ),
        sa.ForeignKeyConstraint(
            ["author_membership_id"],
            ["memberships.id"],
            name=op.f("fk_crm_notes_author_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_crm_notes_customer_id_customers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_crm_notes_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_crm_notes_opportunity_id_opportunities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_crm_notes_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crm_notes")),
    )
    op.create_index(
        "ix_crm_notes_tenant_id_lead_id", "crm_notes", ["tenant_id", "lead_id"], unique=False
    )
    op.create_index(
        "ix_crm_notes_tenant_id_opportunity_id",
        "crm_notes",
        ["tenant_id", "opportunity_id"],
        unique=False,
    )

    for table in TENANT_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table}_updated_at BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION nexora_set_updated_at()"
        )
        # ENABLE only, never FORCE (ADR-0022).
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            "USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid) "
            "WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)"
        )

    connection = op.get_bind()
    for permission in NEW_PERMISSIONS:
        connection.execute(
            sa.text(
                "INSERT INTO permissions (code, description, module) "
                "VALUES (:code, :description, :module) ON CONFLICT (code) DO NOTHING"
            ),
            {
                "code": permission,
                "description": permission.replace(".", " ").title(),
                "module": permission.split(".")[0],
            },
        )
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions DISABLE TRIGGER trg_role_permissions_system_immutable"
    )
    for role_code, permissions in ROLE_PERMISSIONS.items():
        for permission in permissions:
            connection.execute(
                sa.text(
                    "INSERT INTO role_permissions (role_id, permission_code) "
                    "SELECT id, :permission FROM roles WHERE code = :role_code AND is_system"
                ),
                {"role_code": role_code, "permission": permission},
            )
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions ENABLE TRIGGER trg_role_permissions_system_immutable"
    )
    # Permissions are cached by membership roles_version (ADR-0008). Without
    # this bump every logged-in user keeps their old set and each new endpoint
    # 403s for people who genuinely hold the permission — observed after 0013.
    connection.exec_driver_sql("""
        UPDATE memberships SET roles_version = roles_version + 1
         WHERE id IN (
            SELECT mr.membership_id FROM membership_roles mr
              JOIN roles r ON r.id = mr.role_id
             WHERE r.is_system
         )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    connection = op.get_bind()
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions DISABLE TRIGGER trg_role_permissions_system_immutable"
    )
    for permission in PERMISSIONS:
        connection.execute(
            sa.text("DELETE FROM role_permissions WHERE permission_code = :permission"),
            {"permission": permission},
        )
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions ENABLE TRIGGER trg_role_permissions_system_immutable"
    )
    for permission in NEW_PERMISSIONS:
        connection.execute(
            sa.text("DELETE FROM permissions WHERE code = :code"), {"code": permission}
        )
    for table in reversed(TENANT_TABLES):
        op.execute(f"DROP POLICY tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
        op.execute(f"DROP TRIGGER trg_{table}_updated_at ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_crm_notes_tenant_id_opportunity_id", table_name="crm_notes")
    op.drop_index("ix_crm_notes_tenant_id_lead_id", table_name="crm_notes")
    op.drop_table("crm_notes")
    op.drop_index("ix_crm_activities_tenant_id_opportunity_id", table_name="crm_activities")
    op.drop_index("ix_crm_activities_tenant_id_lead_id", table_name="crm_activities")
    op.drop_index("ix_crm_activities_tenant_id_due_at", table_name="crm_activities")
    op.drop_table("crm_activities")
    op.drop_index("ix_opportunities_tenant_id_stage", table_name="opportunities")
    op.drop_index("ix_opportunities_tenant_id_customer_id", table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_index("ix_leads_tenant_id_status", table_name="leads")
    op.drop_index("ix_leads_tenant_id_owner", table_name="leads")
    op.drop_table("leads")
    # ### end Alembic commands ###

    # Dropped last, after every table that uses them.
    for enum_name in (
        "crm_lead_source",
        "crm_lead_status",
        "crm_opportunity_stage",
        "crm_activity_type",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
