"""Phase 7 — VAT rates, register and returns.

DATABASE.md §4 names these three tables. ACCOUNTING.md §9.4: VAT is generic and
no jurisdiction is hardcoded.

Revision ID: e096ec0aa8c0
Revises: 0018_crm
Create Date: 2026-08-30 01:08:19.489949
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0019_vat"
down_revision: str | None = "0018_crm"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = ("vat_rates", "vat_transactions", "vat_returns")

NEW_PERMISSIONS = ("vat.read", "vat.manage", "vat.file")

ROLE_PERMISSIONS = {
    "OWNER": NEW_PERMISSIONS,
    "ADMIN": NEW_PERMISSIONS,
    # Filing is a statement to an authority, so it stays with finance roles.
    "ACCOUNTANT": NEW_PERMISSIONS,
    "MANAGER": ("vat.read",),
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vat_rates",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("rate", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rate >= 0 AND rate <= 1", name=op.f("ck_vat_rates_rate_range")),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from", name=op.f("ck_vat_rates_valid_range")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_vat_rates_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vat_rates")),
        sa.UniqueConstraint(
            "tenant_id", "code", "valid_from", name=op.f("uq_vat_rates_tenant_id_code_valid_from")
        ),
    )
    op.create_index(
        "ix_vat_rates_tenant_id_code_valid_from",
        "vat_rates",
        ["tenant_id", "code", "valid_from"],
        unique=False,
    )
    op.create_table(
        "vat_transactions",
        sa.Column("direction", sa.Enum("OUTPUT", "INPUT", name="vat_direction"), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("rate_code", sa.String(length=32), nullable=True),
        sa.Column("rate", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("taxable_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("vat_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("is_reversal", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("vat_return_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(vat_amount >= 0 AND NOT is_reversal) OR (vat_amount <= 0 AND is_reversal)",
            name=op.f("ck_vat_transactions_reversal_sign"),
        ),
        sa.CheckConstraint("rate >= 0 AND rate <= 1", name=op.f("ck_vat_transactions_rate_range")),
        sa.CheckConstraint(
            "taxable_amount >= 0", name=op.f("ck_vat_transactions_taxable_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_vat_transactions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vat_transactions")),
    )
    op.create_index(
        "ix_vat_transactions_tenant_id_direction",
        "vat_transactions",
        ["tenant_id", "direction"],
        unique=False,
    )
    op.create_index(
        "ix_vat_transactions_tenant_id_occurred_on",
        "vat_transactions",
        ["tenant_id", "occurred_on"],
        unique=False,
    )
    op.create_index(
        "ix_vat_transactions_tenant_id_return_id",
        "vat_transactions",
        ["tenant_id", "vat_return_id"],
        unique=False,
    )
    op.create_table(
        "vat_returns",
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("status", sa.Enum("DRAFT", "FILED", name="vat_return_status"), nullable=False),
        sa.Column(
            "output_vat", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "input_vat", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column("net_vat", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False),
        sa.Column(
            "taxable_sales", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "taxable_purchases",
            sa.Numeric(precision=18, scale=4),
            server_default="0",
            nullable=False,
        ),
        sa.Column("filed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("filed_by_membership_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'FILED' OR filed_at IS NOT NULL",
            name=op.f("ck_vat_returns_filed_return_has_timestamp"),
        ),
        sa.CheckConstraint(
            "output_vat >= 0 AND input_vat >= 0", name=op.f("ck_vat_returns_totals_nonnegative")
        ),
        sa.CheckConstraint("period_end >= period_start", name=op.f("ck_vat_returns_period_range")),
        sa.ForeignKeyConstraint(
            ["filed_by_membership_id"],
            ["memberships.id"],
            name=op.f("fk_vat_returns_filed_by_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_vat_returns_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vat_returns")),
        sa.UniqueConstraint(
            "tenant_id",
            "period_start",
            "period_end",
            name=op.f("uq_vat_returns_tenant_id_period_start_period_end"),
        ),
    )
    op.create_index(
        "ix_vat_returns_tenant_id_status", "vat_returns", ["tenant_id", "status"], unique=False
    )

    for table in TENANT_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table}_updated_at BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION nexora_set_updated_at()"
        )
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            "USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid) "
            "WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)"
        )

    connection = op.get_bind()
    for permission in NEW_PERMISSIONS:
        connection.execute(
            sa.text(
                "INSERT INTO permissions (code, description, module) "
                "VALUES (:code, :description, 'vat') ON CONFLICT (code) DO NOTHING"
            ),
            {"code": permission, "description": permission.replace(".", " ").title()},
        )
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions DISABLE TRIGGER trg_role_permissions_system_immutable"
    )
    for role_code, permissions in ROLE_PERMISSIONS.items():
        for permission in permissions:
            connection.execute(
                sa.text(
                    "INSERT INTO role_permissions (role_id, permission_code) "
                    "SELECT id, :permission FROM roles WHERE code = :role_code AND is_system"
                ),
                {"role_code": role_code, "permission": permission},
            )
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions ENABLE TRIGGER trg_role_permissions_system_immutable"
    )
    # ADR-0008: permissions are cached by roles_version. 0013 taught this.
    connection.exec_driver_sql("""
        UPDATE memberships SET roles_version = roles_version + 1
         WHERE id IN (
            SELECT mr.membership_id FROM membership_roles mr
              JOIN roles r ON r.id = mr.role_id
             WHERE r.is_system
         )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    connection = op.get_bind()
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions DISABLE TRIGGER trg_role_permissions_system_immutable"
    )
    for permission in NEW_PERMISSIONS:
        connection.execute(
            sa.text("DELETE FROM role_permissions WHERE permission_code = :permission"),
            {"permission": permission},
        )
    connection.exec_driver_sql(
        "ALTER TABLE role_permissions ENABLE TRIGGER trg_role_permissions_system_immutable"
    )
    for permission in NEW_PERMISSIONS:
        connection.execute(
            sa.text("DELETE FROM permissions WHERE code = :code"), {"code": permission}
        )
    for table in reversed(TENANT_TABLES):
        op.execute(f"DROP POLICY tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
        op.execute(f"DROP TRIGGER trg_{table}_updated_at ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_vat_returns_tenant_id_status", table_name="vat_returns")
    op.drop_table("vat_returns")
    op.drop_index("ix_vat_transactions_tenant_id_return_id", table_name="vat_transactions")
    op.drop_index("ix_vat_transactions_tenant_id_occurred_on", table_name="vat_transactions")
    op.drop_index("ix_vat_transactions_tenant_id_direction", table_name="vat_transactions")
    op.drop_table("vat_transactions")
    op.drop_index("ix_vat_rates_tenant_id_code_valid_from", table_name="vat_rates")
    op.drop_table("vat_rates")
    # ### end Alembic commands ###

    # Autogenerate never drops enum types; 0012 and 0013 both broke the round
    # trip by omitting this. Dropped last, after the tables that use them.
    for enum_name in ("vat_direction", "vat_return_status"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
